package datos;
// Generated 26/10/2023 15:47:26 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Antecedente generated by hbm2java
 */
public class Antecedente  implements java.io.Serializable {


     private Integer antId;
     private char antTipo;
     private String antGrupo;
     private Date antFechaUlt;
     private String antUsuario;
     private Set personaAntecedentes = new HashSet(0);

    public Antecedente() {
    }

	
    public Antecedente(char antTipo, String antGrupo) {
        this.antTipo = antTipo;
        this.antGrupo = antGrupo;
    }
    public Antecedente(char antTipo, String antGrupo, Date antFechaUlt, String antUsuario, Set personaAntecedentes) {
       this.antTipo = antTipo;
       this.antGrupo = antGrupo;
       this.antFechaUlt = antFechaUlt;
       this.antUsuario = antUsuario;
       this.personaAntecedentes = personaAntecedentes;
    }
   
    public Integer getAntId() {
        return this.antId;
    }
    
    public void setAntId(Integer antId) {
        this.antId = antId;
    }
    public char getAntTipo() {
        return this.antTipo;
    }
    
    public void setAntTipo(char antTipo) {
        this.antTipo = antTipo;
    }
    public String getAntGrupo() {
        return this.antGrupo;
    }
    
    public void setAntGrupo(String antGrupo) {
        this.antGrupo = antGrupo;
    }
    public Date getAntFechaUlt() {
        return this.antFechaUlt;
    }
    
    public void setAntFechaUlt(Date antFechaUlt) {
        this.antFechaUlt = antFechaUlt;
    }
    public String getAntUsuario() {
        return this.antUsuario;
    }
    
    public void setAntUsuario(String antUsuario) {
        this.antUsuario = antUsuario;
    }
    public Set getPersonaAntecedentes() {
        return this.personaAntecedentes;
    }
    
    public void setPersonaAntecedentes(Set personaAntecedentes) {
        this.personaAntecedentes = personaAntecedentes;
    }




}


