package datos;
// Generated 02/12/2023 11:28:58 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Antecedente generated by hbm2java
 */
public class Antecedente  implements java.io.Serializable {


     private Integer antId;
     private char antTipo;
     private String antCategoria;
     private String antGrupo;
     private Date antFechaUlt;
     private String antUsuario;
     private Set historiaAntecedentes = new HashSet(0);

    public Antecedente() {
    }

	
    public Antecedente(char antTipo, String antCategoria, String antGrupo) {
        this.antTipo = antTipo;
        this.antCategoria = antCategoria;
        this.antGrupo = antGrupo;
    }
    public Antecedente(char antTipo, String antCategoria, String antGrupo, Date antFechaUlt, String antUsuario, Set historiaAntecedentes) {
       this.antTipo = antTipo;
       this.antCategoria = antCategoria;
       this.antGrupo = antGrupo;
       this.antFechaUlt = antFechaUlt;
       this.antUsuario = antUsuario;
       this.historiaAntecedentes = historiaAntecedentes;
    }
   
    public Integer getAntId() {
        return this.antId;
    }
    
    public void setAntId(Integer antId) {
        this.antId = antId;
    }
    public char getAntTipo() {
        return this.antTipo;
    }
    
    public void setAntTipo(char antTipo) {
        this.antTipo = antTipo;
    }
    public String getAntCategoria() {
        return this.antCategoria;
    }
    
    public void setAntCategoria(String antCategoria) {
        this.antCategoria = antCategoria;
    }
    public String getAntGrupo() {
        return this.antGrupo;
    }
    
    public void setAntGrupo(String antGrupo) {
        this.antGrupo = antGrupo;
    }
    public Date getAntFechaUlt() {
        return this.antFechaUlt;
    }
    
    public void setAntFechaUlt(Date antFechaUlt) {
        this.antFechaUlt = antFechaUlt;
    }
    public String getAntUsuario() {
        return this.antUsuario;
    }
    
    public void setAntUsuario(String antUsuario) {
        this.antUsuario = antUsuario;
    }
    public Set getHistoriaAntecedentes() {
        return this.historiaAntecedentes;
    }
    
    public void setHistoriaAntecedentes(Set historiaAntecedentes) {
        this.historiaAntecedentes = historiaAntecedentes;
    }




}


