package datos;
// Generated 22-jun-2023 9:54:18 by Hibernate Tools 4.3.1



/**
 * Dummy generated by hbm2java
 */
public class Dummy  implements java.io.Serializable {


     private Integer id;
     private String codigo;

    public Dummy() {
    }

    public Dummy(String codigo) {
       this.codigo = codigo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }




}


