package datos;
// Generated 04/12/2023 14:37:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Examenes generated by hbm2java
 */
public class Examenes  implements java.io.Serializable {


     private Integer exaId;
     private char exaTipo;
     private String exaGrupo;
     private Date exaFechaUlt;
     private String exaUsuario;
     private Set historiaExamens = new HashSet(0);

    public Examenes() {
    }

	
    public Examenes(char exaTipo, String exaGrupo) {
        this.exaTipo = exaTipo;
        this.exaGrupo = exaGrupo;
    }
    public Examenes(char exaTipo, String exaGrupo, Date exaFechaUlt, String exaUsuario, Set historiaExamens) {
       this.exaTipo = exaTipo;
       this.exaGrupo = exaGrupo;
       this.exaFechaUlt = exaFechaUlt;
       this.exaUsuario = exaUsuario;
       this.historiaExamens = historiaExamens;
    }
   
    public Integer getExaId() {
        return this.exaId;
    }
    
    public void setExaId(Integer exaId) {
        this.exaId = exaId;
    }
    public char getExaTipo() {
        return this.exaTipo;
    }
    
    public void setExaTipo(char exaTipo) {
        this.exaTipo = exaTipo;
    }
    public String getExaGrupo() {
        return this.exaGrupo;
    }
    
    public void setExaGrupo(String exaGrupo) {
        this.exaGrupo = exaGrupo;
    }
    public Date getExaFechaUlt() {
        return this.exaFechaUlt;
    }
    
    public void setExaFechaUlt(Date exaFechaUlt) {
        this.exaFechaUlt = exaFechaUlt;
    }
    public String getExaUsuario() {
        return this.exaUsuario;
    }
    
    public void setExaUsuario(String exaUsuario) {
        this.exaUsuario = exaUsuario;
    }
    public Set getHistoriaExamens() {
        return this.historiaExamens;
    }
    
    public void setHistoriaExamens(Set historiaExamens) {
        this.historiaExamens = historiaExamens;
    }




}


