package datos;
// Generated 04/12/2023 14:37:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Historias generated by hbm2java
 */
public class Historias  implements java.io.Serializable {


     private Integer hisId;
     private Enfermedades enfermedades;
     private Personas personasByMedicoPerId;
     private Personas personasByPacientePerId;
     private Resultados resultados;
     private RevisionSistemas revisionSistemas;
     private Signos signos;
     private String hisMotivo;
     private String hisEnfermedad;
     private String hisExamenGeneral;
     private String hisExamenNeurologico;
     private String hisIndicaciones;
     private Date hisFechaCreacion;
     private Date hisFechaUlt;
     private String hisUsuario;
     private Byte hisCompletado;
     private Set historiaTratamientos = new HashSet(0);
     private Set enfermedadeses = new HashSet(0);
     private Set historiaDiagnosticos = new HashSet(0);
     private Set historiaAntecedentes = new HashSet(0);
     private Set historiaExamens = new HashSet(0);

    public Historias() {
    }

	
    public Historias(Personas personasByPacientePerId, String hisMotivo, String hisEnfermedad, Date hisFechaCreacion) {
        this.personasByPacientePerId = personasByPacientePerId;
        this.hisMotivo = hisMotivo;
        this.hisEnfermedad = hisEnfermedad;
        this.hisFechaCreacion = hisFechaCreacion;
    }
    public Historias(Enfermedades enfermedades, Personas personasByMedicoPerId, Personas personasByPacientePerId, Resultados resultados, RevisionSistemas revisionSistemas, Signos signos, String hisMotivo, String hisEnfermedad, String hisExamenGeneral, String hisExamenNeurologico, String hisIndicaciones, Date hisFechaCreacion, Date hisFechaUlt, String hisUsuario, Byte hisCompletado, Set historiaTratamientos, Set enfermedadeses, Set historiaDiagnosticos, Set historiaAntecedentes, Set historiaExamens) {
       this.enfermedades = enfermedades;
       this.personasByMedicoPerId = personasByMedicoPerId;
       this.personasByPacientePerId = personasByPacientePerId;
       this.resultados = resultados;
       this.revisionSistemas = revisionSistemas;
       this.signos = signos;
       this.hisMotivo = hisMotivo;
       this.hisEnfermedad = hisEnfermedad;
       this.hisExamenGeneral = hisExamenGeneral;
       this.hisExamenNeurologico = hisExamenNeurologico;
       this.hisIndicaciones = hisIndicaciones;
       this.hisFechaCreacion = hisFechaCreacion;
       this.hisFechaUlt = hisFechaUlt;
       this.hisUsuario = hisUsuario;
       this.hisCompletado = hisCompletado;
       this.historiaTratamientos = historiaTratamientos;
       this.enfermedadeses = enfermedadeses;
       this.historiaDiagnosticos = historiaDiagnosticos;
       this.historiaAntecedentes = historiaAntecedentes;
       this.historiaExamens = historiaExamens;
    }
   
    public Integer getHisId() {
        return this.hisId;
    }
    
    public void setHisId(Integer hisId) {
        this.hisId = hisId;
    }
    public Enfermedades getEnfermedades() {
        return this.enfermedades;
    }
    
    public void setEnfermedades(Enfermedades enfermedades) {
        this.enfermedades = enfermedades;
    }
    public Personas getPersonasByMedicoPerId() {
        return this.personasByMedicoPerId;
    }
    
    public void setPersonasByMedicoPerId(Personas personasByMedicoPerId) {
        this.personasByMedicoPerId = personasByMedicoPerId;
    }
    public Personas getPersonasByPacientePerId() {
        return this.personasByPacientePerId;
    }
    
    public void setPersonasByPacientePerId(Personas personasByPacientePerId) {
        this.personasByPacientePerId = personasByPacientePerId;
    }
    public Resultados getResultados() {
        return this.resultados;
    }
    
    public void setResultados(Resultados resultados) {
        this.resultados = resultados;
    }
    public RevisionSistemas getRevisionSistemas() {
        return this.revisionSistemas;
    }
    
    public void setRevisionSistemas(RevisionSistemas revisionSistemas) {
        this.revisionSistemas = revisionSistemas;
    }
    public Signos getSignos() {
        return this.signos;
    }
    
    public void setSignos(Signos signos) {
        this.signos = signos;
    }
    public String getHisMotivo() {
        return this.hisMotivo;
    }
    
    public void setHisMotivo(String hisMotivo) {
        this.hisMotivo = hisMotivo;
    }
    public String getHisEnfermedad() {
        return this.hisEnfermedad;
    }
    
    public void setHisEnfermedad(String hisEnfermedad) {
        this.hisEnfermedad = hisEnfermedad;
    }
    public String getHisExamenGeneral() {
        return this.hisExamenGeneral;
    }
    
    public void setHisExamenGeneral(String hisExamenGeneral) {
        this.hisExamenGeneral = hisExamenGeneral;
    }
    public String getHisExamenNeurologico() {
        return this.hisExamenNeurologico;
    }
    
    public void setHisExamenNeurologico(String hisExamenNeurologico) {
        this.hisExamenNeurologico = hisExamenNeurologico;
    }
    public String getHisIndicaciones() {
        return this.hisIndicaciones;
    }
    
    public void setHisIndicaciones(String hisIndicaciones) {
        this.hisIndicaciones = hisIndicaciones;
    }
    public Date getHisFechaCreacion() {
        return this.hisFechaCreacion;
    }
    
    public void setHisFechaCreacion(Date hisFechaCreacion) {
        this.hisFechaCreacion = hisFechaCreacion;
    }
    public Date getHisFechaUlt() {
        return this.hisFechaUlt;
    }
    
    public void setHisFechaUlt(Date hisFechaUlt) {
        this.hisFechaUlt = hisFechaUlt;
    }
    public String getHisUsuario() {
        return this.hisUsuario;
    }
    
    public void setHisUsuario(String hisUsuario) {
        this.hisUsuario = hisUsuario;
    }
    public Byte getHisCompletado() {
        return this.hisCompletado;
    }
    
    public void setHisCompletado(Byte hisCompletado) {
        this.hisCompletado = hisCompletado;
    }
    public Set getHistoriaTratamientos() {
        return this.historiaTratamientos;
    }
    
    public void setHistoriaTratamientos(Set historiaTratamientos) {
        this.historiaTratamientos = historiaTratamientos;
    }
    public Set getEnfermedadeses() {
        return this.enfermedadeses;
    }
    
    public void setEnfermedadeses(Set enfermedadeses) {
        this.enfermedadeses = enfermedadeses;
    }
    public Set getHistoriaDiagnosticos() {
        return this.historiaDiagnosticos;
    }
    
    public void setHistoriaDiagnosticos(Set historiaDiagnosticos) {
        this.historiaDiagnosticos = historiaDiagnosticos;
    }
    public Set getHistoriaAntecedentes() {
        return this.historiaAntecedentes;
    }
    
    public void setHistoriaAntecedentes(Set historiaAntecedentes) {
        this.historiaAntecedentes = historiaAntecedentes;
    }
    public Set getHistoriaExamens() {
        return this.historiaExamens;
    }
    
    public void setHistoriaExamens(Set historiaExamens) {
        this.historiaExamens = historiaExamens;
    }




}


