package datos;
// Generated 08/12/2023 15:38:39 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HistoriaDiagnostico generated by hbm2java
 */
public class HistoriaDiagnostico  implements java.io.Serializable {


     private Integer hisDiaId;
     private Diagnosticos diagnosticos;
     private Historias historias;
     private String hisDiaObservacion;
     private String hisDiaTipo;
     private String hisDiaCondicion;
     private String hisDiaCronologia;
     private Date hisDiaFechaUlt;
     private String hisDiaUsuario;
     private Set historiaTratamientos = new HashSet(0);

    public HistoriaDiagnostico() {
    }

	
    public HistoriaDiagnostico(Diagnosticos diagnosticos, Historias historias, String hisDiaObservacion, String hisDiaTipo, String hisDiaCondicion, String hisDiaCronologia, Date hisDiaFechaUlt, String hisDiaUsuario) {
        this.diagnosticos = diagnosticos;
        this.historias = historias;
        this.hisDiaObservacion = hisDiaObservacion;
        this.hisDiaTipo = hisDiaTipo;
        this.hisDiaCondicion = hisDiaCondicion;
        this.hisDiaCronologia = hisDiaCronologia;
        this.hisDiaFechaUlt = hisDiaFechaUlt;
        this.hisDiaUsuario = hisDiaUsuario;
    }
    public HistoriaDiagnostico(Diagnosticos diagnosticos, Historias historias, String hisDiaObservacion, String hisDiaTipo, String hisDiaCondicion, String hisDiaCronologia, Date hisDiaFechaUlt, String hisDiaUsuario, Set historiaTratamientos) {
       this.diagnosticos = diagnosticos;
       this.historias = historias;
       this.hisDiaObservacion = hisDiaObservacion;
       this.hisDiaTipo = hisDiaTipo;
       this.hisDiaCondicion = hisDiaCondicion;
       this.hisDiaCronologia = hisDiaCronologia;
       this.hisDiaFechaUlt = hisDiaFechaUlt;
       this.hisDiaUsuario = hisDiaUsuario;
       this.historiaTratamientos = historiaTratamientos;
    }
   
    public Integer getHisDiaId() {
        return this.hisDiaId;
    }
    
    public void setHisDiaId(Integer hisDiaId) {
        this.hisDiaId = hisDiaId;
    }
    public Diagnosticos getDiagnosticos() {
        return this.diagnosticos;
    }
    
    public void setDiagnosticos(Diagnosticos diagnosticos) {
        this.diagnosticos = diagnosticos;
    }
    public Historias getHistorias() {
        return this.historias;
    }
    
    public void setHistorias(Historias historias) {
        this.historias = historias;
    }
    public String getHisDiaObservacion() {
        return this.hisDiaObservacion;
    }
    
    public void setHisDiaObservacion(String hisDiaObservacion) {
        this.hisDiaObservacion = hisDiaObservacion;
    }
    public String getHisDiaTipo() {
        return this.hisDiaTipo;
    }
    
    public void setHisDiaTipo(String hisDiaTipo) {
        this.hisDiaTipo = hisDiaTipo;
    }
    public String getHisDiaCondicion() {
        return this.hisDiaCondicion;
    }
    
    public void setHisDiaCondicion(String hisDiaCondicion) {
        this.hisDiaCondicion = hisDiaCondicion;
    }
    public String getHisDiaCronologia() {
        return this.hisDiaCronologia;
    }
    
    public void setHisDiaCronologia(String hisDiaCronologia) {
        this.hisDiaCronologia = hisDiaCronologia;
    }
    public Date getHisDiaFechaUlt() {
        return this.hisDiaFechaUlt;
    }
    
    public void setHisDiaFechaUlt(Date hisDiaFechaUlt) {
        this.hisDiaFechaUlt = hisDiaFechaUlt;
    }
    public String getHisDiaUsuario() {
        return this.hisDiaUsuario;
    }
    
    public void setHisDiaUsuario(String hisDiaUsuario) {
        this.hisDiaUsuario = hisDiaUsuario;
    }
    public Set getHistoriaTratamientos() {
        return this.historiaTratamientos;
    }
    
    public void setHistoriaTratamientos(Set historiaTratamientos) {
        this.historiaTratamientos = historiaTratamientos;
    }




}


