package datos;
// Generated 24/11/2023 11:56:23 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * HistoriaAntecedente generated by hbm2java
 */
public class HistoriaAntecedente  implements java.io.Serializable {


     private Integer perAntId;
     private Antecedente antecedente;
     private Historias historias;
     private String perAntDescripcion;
     private Date perAntFechaUlt;
     private String perAntUsuario;

    public HistoriaAntecedente() {
    }

    public HistoriaAntecedente(Antecedente antecedente, Historias historias, String perAntDescripcion, Date perAntFechaUlt, String perAntUsuario) {
       this.antecedente = antecedente;
       this.historias = historias;
       this.perAntDescripcion = perAntDescripcion;
       this.perAntFechaUlt = perAntFechaUlt;
       this.perAntUsuario = perAntUsuario;
    }
   
    public Integer getPerAntId() {
        return this.perAntId;
    }
    
    public void setPerAntId(Integer perAntId) {
        this.perAntId = perAntId;
    }
    public Antecedente getAntecedente() {
        return this.antecedente;
    }
    
    public void setAntecedente(Antecedente antecedente) {
        this.antecedente = antecedente;
    }
    public Historias getHistorias() {
        return this.historias;
    }
    
    public void setHistorias(Historias historias) {
        this.historias = historias;
    }
    public String getPerAntDescripcion() {
        return this.perAntDescripcion;
    }
    
    public void setPerAntDescripcion(String perAntDescripcion) {
        this.perAntDescripcion = perAntDescripcion;
    }
    public Date getPerAntFechaUlt() {
        return this.perAntFechaUlt;
    }
    
    public void setPerAntFechaUlt(Date perAntFechaUlt) {
        this.perAntFechaUlt = perAntFechaUlt;
    }
    public String getPerAntUsuario() {
        return this.perAntUsuario;
    }
    
    public void setPerAntUsuario(String perAntUsuario) {
        this.perAntUsuario = perAntUsuario;
    }




}


