package datos;
// Generated 02/12/2023 11:28:58 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * HistoriaTratamiento generated by hbm2java
 */
public class HistoriaTratamiento  implements java.io.Serializable {


     private Integer hisTraId;
     private Historias historias;
     private Tratamientos tratamientos;
     private Date hisTraFechaUlt;
     private String hisTraUsuario;

    public HistoriaTratamiento() {
    }

    public HistoriaTratamiento(Historias historias, Tratamientos tratamientos, Date hisTraFechaUlt, String hisTraUsuario) {
       this.historias = historias;
       this.tratamientos = tratamientos;
       this.hisTraFechaUlt = hisTraFechaUlt;
       this.hisTraUsuario = hisTraUsuario;
    }
   
    public Integer getHisTraId() {
        return this.hisTraId;
    }
    
    public void setHisTraId(Integer hisTraId) {
        this.hisTraId = hisTraId;
    }
    public Historias getHistorias() {
        return this.historias;
    }
    
    public void setHistorias(Historias historias) {
        this.historias = historias;
    }
    public Tratamientos getTratamientos() {
        return this.tratamientos;
    }
    
    public void setTratamientos(Tratamientos tratamientos) {
        this.tratamientos = tratamientos;
    }
    public Date getHisTraFechaUlt() {
        return this.hisTraFechaUlt;
    }
    
    public void setHisTraFechaUlt(Date hisTraFechaUlt) {
        this.hisTraFechaUlt = hisTraFechaUlt;
    }
    public String getHisTraUsuario() {
        return this.hisTraUsuario;
    }
    
    public void setHisTraUsuario(String hisTraUsuario) {
        this.hisTraUsuario = hisTraUsuario;
    }




}


