package datos;
// Generated 24/11/2023 11:56:23 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * HistoriaExamen generated by hbm2java
 */
public class HistoriaExamen  implements java.io.Serializable {


     private Integer perExaId;
     private Examenes examenes;
     private Historias historias;
     private String perExaDescripcion;
     private Date perExaFecha;
     private Date perExaFechaUlt;
     private String perExaUsuario;
     private Byte perExaCompletado;

    public HistoriaExamen() {
    }

	
    public HistoriaExamen(Examenes examenes, Historias historias, String perExaDescripcion, Date perExaFecha, Date perExaFechaUlt, String perExaUsuario) {
        this.examenes = examenes;
        this.historias = historias;
        this.perExaDescripcion = perExaDescripcion;
        this.perExaFecha = perExaFecha;
        this.perExaFechaUlt = perExaFechaUlt;
        this.perExaUsuario = perExaUsuario;
    }
    public HistoriaExamen(Examenes examenes, Historias historias, String perExaDescripcion, Date perExaFecha, Date perExaFechaUlt, String perExaUsuario, Byte perExaCompletado) {
       this.examenes = examenes;
       this.historias = historias;
       this.perExaDescripcion = perExaDescripcion;
       this.perExaFecha = perExaFecha;
       this.perExaFechaUlt = perExaFechaUlt;
       this.perExaUsuario = perExaUsuario;
       this.perExaCompletado = perExaCompletado;
    }
   
    public Integer getPerExaId() {
        return this.perExaId;
    }
    
    public void setPerExaId(Integer perExaId) {
        this.perExaId = perExaId;
    }
    public Examenes getExamenes() {
        return this.examenes;
    }
    
    public void setExamenes(Examenes examenes) {
        this.examenes = examenes;
    }
    public Historias getHistorias() {
        return this.historias;
    }
    
    public void setHistorias(Historias historias) {
        this.historias = historias;
    }
    public String getPerExaDescripcion() {
        return this.perExaDescripcion;
    }
    
    public void setPerExaDescripcion(String perExaDescripcion) {
        this.perExaDescripcion = perExaDescripcion;
    }
    public Date getPerExaFecha() {
        return this.perExaFecha;
    }
    
    public void setPerExaFecha(Date perExaFecha) {
        this.perExaFecha = perExaFecha;
    }
    public Date getPerExaFechaUlt() {
        return this.perExaFechaUlt;
    }
    
    public void setPerExaFechaUlt(Date perExaFechaUlt) {
        this.perExaFechaUlt = perExaFechaUlt;
    }
    public String getPerExaUsuario() {
        return this.perExaUsuario;
    }
    
    public void setPerExaUsuario(String perExaUsuario) {
        this.perExaUsuario = perExaUsuario;
    }
    public Byte getPerExaCompletado() {
        return this.perExaCompletado;
    }
    
    public void setPerExaCompletado(Byte perExaCompletado) {
        this.perExaCompletado = perExaCompletado;
    }




}


