package datos;
// Generated 30/10/2023 8:25:50 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Medicamentos generated by hbm2java
 */
public class Medicamentos  implements java.io.Serializable {


     private Integer medId;
     private Tratamientos tratamientos;
     private String medNombre;
     private Date medFechaUlt;
     private String medUsuario;

    public Medicamentos() {
    }

    public Medicamentos(Tratamientos tratamientos, String medNombre, Date medFechaUlt, String medUsuario) {
       this.tratamientos = tratamientos;
       this.medNombre = medNombre;
       this.medFechaUlt = medFechaUlt;
       this.medUsuario = medUsuario;
    }
   
    public Integer getMedId() {
        return this.medId;
    }
    
    public void setMedId(Integer medId) {
        this.medId = medId;
    }
    public Tratamientos getTratamientos() {
        return this.tratamientos;
    }
    
    public void setTratamientos(Tratamientos tratamientos) {
        this.tratamientos = tratamientos;
    }
    public String getMedNombre() {
        return this.medNombre;
    }
    
    public void setMedNombre(String medNombre) {
        this.medNombre = medNombre;
    }
    public Date getMedFechaUlt() {
        return this.medFechaUlt;
    }
    
    public void setMedFechaUlt(Date medFechaUlt) {
        this.medFechaUlt = medFechaUlt;
    }
    public String getMedUsuario() {
        return this.medUsuario;
    }
    
    public void setMedUsuario(String medUsuario) {
        this.medUsuario = medUsuario;
    }




}


