package datos;
// Generated 26/10/2023 15:47:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PersonaAntecedente generated by hbm2java
 */
public class PersonaAntecedente  implements java.io.Serializable {


     private Integer perAntId;
     private Antecedente antecedente;
     private Personas personasByMedPerId;
     private Personas personasByPerId;
     private String perAntDescripcion;
     private Date perAntFechaUlt;
     private String perAntUsuario;

    public PersonaAntecedente() {
    }

    public PersonaAntecedente(Antecedente antecedente, Personas personasByMedPerId, Personas personasByPerId, String perAntDescripcion, Date perAntFechaUlt, String perAntUsuario) {
       this.antecedente = antecedente;
       this.personasByMedPerId = personasByMedPerId;
       this.personasByPerId = personasByPerId;
       this.perAntDescripcion = perAntDescripcion;
       this.perAntFechaUlt = perAntFechaUlt;
       this.perAntUsuario = perAntUsuario;
    }
   
    public Integer getPerAntId() {
        return this.perAntId;
    }
    
    public void setPerAntId(Integer perAntId) {
        this.perAntId = perAntId;
    }
    public Antecedente getAntecedente() {
        return this.antecedente;
    }
    
    public void setAntecedente(Antecedente antecedente) {
        this.antecedente = antecedente;
    }
    public Personas getPersonasByMedPerId() {
        return this.personasByMedPerId;
    }
    
    public void setPersonasByMedPerId(Personas personasByMedPerId) {
        this.personasByMedPerId = personasByMedPerId;
    }
    public Personas getPersonasByPerId() {
        return this.personasByPerId;
    }
    
    public void setPersonasByPerId(Personas personasByPerId) {
        this.personasByPerId = personasByPerId;
    }
    public String getPerAntDescripcion() {
        return this.perAntDescripcion;
    }
    
    public void setPerAntDescripcion(String perAntDescripcion) {
        this.perAntDescripcion = perAntDescripcion;
    }
    public Date getPerAntFechaUlt() {
        return this.perAntFechaUlt;
    }
    
    public void setPerAntFechaUlt(Date perAntFechaUlt) {
        this.perAntFechaUlt = perAntFechaUlt;
    }
    public String getPerAntUsuario() {
        return this.perAntUsuario;
    }
    
    public void setPerAntUsuario(String perAntUsuario) {
        this.perAntUsuario = perAntUsuario;
    }




}


