package datos;
// Generated 18-abr-2023 17:26:24 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personas generated by hbm2java
 */
public class Personas  implements java.io.Serializable {


     private Integer perId;
     private String perNombres;
     private String perApellidos;
     private char perSexo;
     private Date perNac;
     private String perGrupoSanguineo;
     private Character perIdentidadGenero;
     private int perProfesion;
     private Date perFechaUlt;
     private String perUsuario;
     private Set historiases = new HashSet(0);
     private Set usuarioses = new HashSet(0);
     private Set antecedenteses = new HashSet(0);

    public Personas() {
    }

	
    public Personas(String perNombres, String perApellidos, char perSexo, Date perNac, String perGrupoSanguineo, int perProfesion, Date perFechaUlt, String perUsuario) {
        this.perNombres = perNombres;
        this.perApellidos = perApellidos;
        this.perSexo = perSexo;
        this.perNac = perNac;
        this.perGrupoSanguineo = perGrupoSanguineo;
        this.perProfesion = perProfesion;
        this.perFechaUlt = perFechaUlt;
        this.perUsuario = perUsuario;
    }
    public Personas(String perNombres, String perApellidos, char perSexo, Date perNac, String perGrupoSanguineo, Character perIdentidadGenero, int perProfesion, Date perFechaUlt, String perUsuario, Set historiases, Set usuarioses, Set antecedenteses) {
       this.perNombres = perNombres;
       this.perApellidos = perApellidos;
       this.perSexo = perSexo;
       this.perNac = perNac;
       this.perGrupoSanguineo = perGrupoSanguineo;
       this.perIdentidadGenero = perIdentidadGenero;
       this.perProfesion = perProfesion;
       this.perFechaUlt = perFechaUlt;
       this.perUsuario = perUsuario;
       this.historiases = historiases;
       this.usuarioses = usuarioses;
       this.antecedenteses = antecedenteses;
    }
   
    public Integer getPerId() {
        return this.perId;
    }
    
    public void setPerId(Integer perId) {
        this.perId = perId;
    }
    public String getPerNombres() {
        return this.perNombres;
    }
    
    public void setPerNombres(String perNombres) {
        this.perNombres = perNombres;
    }
    public String getPerApellidos() {
        return this.perApellidos;
    }
    
    public void setPerApellidos(String perApellidos) {
        this.perApellidos = perApellidos;
    }
    public char getPerSexo() {
        return this.perSexo;
    }
    
    public void setPerSexo(char perSexo) {
        this.perSexo = perSexo;
    }
    public Date getPerNac() {
        return this.perNac;
    }
    
    public void setPerNac(Date perNac) {
        this.perNac = perNac;
    }
    public String getPerGrupoSanguineo() {
        return this.perGrupoSanguineo;
    }
    
    public void setPerGrupoSanguineo(String perGrupoSanguineo) {
        this.perGrupoSanguineo = perGrupoSanguineo;
    }
    public Character getPerIdentidadGenero() {
        return this.perIdentidadGenero;
    }
    
    public void setPerIdentidadGenero(Character perIdentidadGenero) {
        this.perIdentidadGenero = perIdentidadGenero;
    }
    public int getPerProfesion() {
        return this.perProfesion;
    }
    
    public void setPerProfesion(int perProfesion) {
        this.perProfesion = perProfesion;
    }
    public Date getPerFechaUlt() {
        return this.perFechaUlt;
    }
    
    public void setPerFechaUlt(Date perFechaUlt) {
        this.perFechaUlt = perFechaUlt;
    }
    public String getPerUsuario() {
        return this.perUsuario;
    }
    
    public void setPerUsuario(String perUsuario) {
        this.perUsuario = perUsuario;
    }
    public Set getHistoriases() {
        return this.historiases;
    }
    
    public void setHistoriases(Set historiases) {
        this.historiases = historiases;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }
    public Set getAntecedenteses() {
        return this.antecedenteses;
    }
    
    public void setAntecedenteses(Set antecedenteses) {
        this.antecedenteses = antecedenteses;
    }




}


