package datos;
// Generated 30/10/2023 8:25:50 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PersonaExamen generated by hbm2java
 */
public class PersonaExamen  implements java.io.Serializable {


     private Integer perExaId;
     private Examenes examenes;
     private Personas personasByPerId;
     private Personas personasByMedPerId;
     private String perExaDescripcion;
     private Date perExaFechaUlt;
     private String perExaUsuario;

    public PersonaExamen() {
    }

    public PersonaExamen(Examenes examenes, Personas personasByPerId, Personas personasByMedPerId, String perExaDescripcion, Date perExaFechaUlt, String perExaUsuario) {
       this.examenes = examenes;
       this.personasByPerId = personasByPerId;
       this.personasByMedPerId = personasByMedPerId;
       this.perExaDescripcion = perExaDescripcion;
       this.perExaFechaUlt = perExaFechaUlt;
       this.perExaUsuario = perExaUsuario;
    }
   
    public Integer getPerExaId() {
        return this.perExaId;
    }
    
    public void setPerExaId(Integer perExaId) {
        this.perExaId = perExaId;
    }
    public Examenes getExamenes() {
        return this.examenes;
    }
    
    public void setExamenes(Examenes examenes) {
        this.examenes = examenes;
    }
    public Personas getPersonasByPerId() {
        return this.personasByPerId;
    }
    
    public void setPersonasByPerId(Personas personasByPerId) {
        this.personasByPerId = personasByPerId;
    }
    public Personas getPersonasByMedPerId() {
        return this.personasByMedPerId;
    }
    
    public void setPersonasByMedPerId(Personas personasByMedPerId) {
        this.personasByMedPerId = personasByMedPerId;
    }
    public String getPerExaDescripcion() {
        return this.perExaDescripcion;
    }
    
    public void setPerExaDescripcion(String perExaDescripcion) {
        this.perExaDescripcion = perExaDescripcion;
    }
    public Date getPerExaFechaUlt() {
        return this.perExaFechaUlt;
    }
    
    public void setPerExaFechaUlt(Date perExaFechaUlt) {
        this.perExaFechaUlt = perExaFechaUlt;
    }
    public String getPerExaUsuario() {
        return this.perExaUsuario;
    }
    
    public void setPerExaUsuario(String perExaUsuario) {
        this.perExaUsuario = perExaUsuario;
    }




}


