package datos;
// Generated 17-abr-2023 10:51:47 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RevisionSistemas generated by hbm2java
 */
public class RevisionSistemas  implements java.io.Serializable {


     private Integer revSisId;
     private char revSisPatologia;
     private char revSisSentidos;
     private char revSisRespiratorio;
     private Character revSisCardiovascular;
     private char revSisDigestivo;
     private char revSisGenital;
     private char revSisUrinario;
     private char revSisEsqueletico;
     private char revSisMuscular;
     private char revSisNervioso;
     private char revSisEndocrino;
     private Character revSisHemolinfatico;
     private Character revSisTegumentario;
     private char revSisFisicoPatologia;
     private String revSisFisicoObservacion;
     private Date revSisFechaUlt;
     private String revSisUsuario;
     private Set historiases = new HashSet(0);

    public RevisionSistemas() {
    }

	
    public RevisionSistemas(char revSisPatologia, char revSisSentidos, char revSisRespiratorio, char revSisDigestivo, char revSisGenital, char revSisUrinario, char revSisEsqueletico, char revSisMuscular, char revSisNervioso, char revSisEndocrino, char revSisFisicoPatologia, String revSisFisicoObservacion, Date revSisFechaUlt, String revSisUsuario) {
        this.revSisPatologia = revSisPatologia;
        this.revSisSentidos = revSisSentidos;
        this.revSisRespiratorio = revSisRespiratorio;
        this.revSisDigestivo = revSisDigestivo;
        this.revSisGenital = revSisGenital;
        this.revSisUrinario = revSisUrinario;
        this.revSisEsqueletico = revSisEsqueletico;
        this.revSisMuscular = revSisMuscular;
        this.revSisNervioso = revSisNervioso;
        this.revSisEndocrino = revSisEndocrino;
        this.revSisFisicoPatologia = revSisFisicoPatologia;
        this.revSisFisicoObservacion = revSisFisicoObservacion;
        this.revSisFechaUlt = revSisFechaUlt;
        this.revSisUsuario = revSisUsuario;
    }
    public RevisionSistemas(char revSisPatologia, char revSisSentidos, char revSisRespiratorio, Character revSisCardiovascular, char revSisDigestivo, char revSisGenital, char revSisUrinario, char revSisEsqueletico, char revSisMuscular, char revSisNervioso, char revSisEndocrino, Character revSisHemolinfatico, Character revSisTegumentario, char revSisFisicoPatologia, String revSisFisicoObservacion, Date revSisFechaUlt, String revSisUsuario, Set historiases) {
       this.revSisPatologia = revSisPatologia;
       this.revSisSentidos = revSisSentidos;
       this.revSisRespiratorio = revSisRespiratorio;
       this.revSisCardiovascular = revSisCardiovascular;
       this.revSisDigestivo = revSisDigestivo;
       this.revSisGenital = revSisGenital;
       this.revSisUrinario = revSisUrinario;
       this.revSisEsqueletico = revSisEsqueletico;
       this.revSisMuscular = revSisMuscular;
       this.revSisNervioso = revSisNervioso;
       this.revSisEndocrino = revSisEndocrino;
       this.revSisHemolinfatico = revSisHemolinfatico;
       this.revSisTegumentario = revSisTegumentario;
       this.revSisFisicoPatologia = revSisFisicoPatologia;
       this.revSisFisicoObservacion = revSisFisicoObservacion;
       this.revSisFechaUlt = revSisFechaUlt;
       this.revSisUsuario = revSisUsuario;
       this.historiases = historiases;
    }
   
    public Integer getRevSisId() {
        return this.revSisId;
    }
    
    public void setRevSisId(Integer revSisId) {
        this.revSisId = revSisId;
    }
    public char getRevSisPatologia() {
        return this.revSisPatologia;
    }
    
    public void setRevSisPatologia(char revSisPatologia) {
        this.revSisPatologia = revSisPatologia;
    }
    public char getRevSisSentidos() {
        return this.revSisSentidos;
    }
    
    public void setRevSisSentidos(char revSisSentidos) {
        this.revSisSentidos = revSisSentidos;
    }
    public char getRevSisRespiratorio() {
        return this.revSisRespiratorio;
    }
    
    public void setRevSisRespiratorio(char revSisRespiratorio) {
        this.revSisRespiratorio = revSisRespiratorio;
    }
    public Character getRevSisCardiovascular() {
        return this.revSisCardiovascular;
    }
    
    public void setRevSisCardiovascular(Character revSisCardiovascular) {
        this.revSisCardiovascular = revSisCardiovascular;
    }
    public char getRevSisDigestivo() {
        return this.revSisDigestivo;
    }
    
    public void setRevSisDigestivo(char revSisDigestivo) {
        this.revSisDigestivo = revSisDigestivo;
    }
    public char getRevSisGenital() {
        return this.revSisGenital;
    }
    
    public void setRevSisGenital(char revSisGenital) {
        this.revSisGenital = revSisGenital;
    }
    public char getRevSisUrinario() {
        return this.revSisUrinario;
    }
    
    public void setRevSisUrinario(char revSisUrinario) {
        this.revSisUrinario = revSisUrinario;
    }
    public char getRevSisEsqueletico() {
        return this.revSisEsqueletico;
    }
    
    public void setRevSisEsqueletico(char revSisEsqueletico) {
        this.revSisEsqueletico = revSisEsqueletico;
    }
    public char getRevSisMuscular() {
        return this.revSisMuscular;
    }
    
    public void setRevSisMuscular(char revSisMuscular) {
        this.revSisMuscular = revSisMuscular;
    }
    public char getRevSisNervioso() {
        return this.revSisNervioso;
    }
    
    public void setRevSisNervioso(char revSisNervioso) {
        this.revSisNervioso = revSisNervioso;
    }
    public char getRevSisEndocrino() {
        return this.revSisEndocrino;
    }
    
    public void setRevSisEndocrino(char revSisEndocrino) {
        this.revSisEndocrino = revSisEndocrino;
    }
    public Character getRevSisHemolinfatico() {
        return this.revSisHemolinfatico;
    }
    
    public void setRevSisHemolinfatico(Character revSisHemolinfatico) {
        this.revSisHemolinfatico = revSisHemolinfatico;
    }
    public Character getRevSisTegumentario() {
        return this.revSisTegumentario;
    }
    
    public void setRevSisTegumentario(Character revSisTegumentario) {
        this.revSisTegumentario = revSisTegumentario;
    }
    public char getRevSisFisicoPatologia() {
        return this.revSisFisicoPatologia;
    }
    
    public void setRevSisFisicoPatologia(char revSisFisicoPatologia) {
        this.revSisFisicoPatologia = revSisFisicoPatologia;
    }
    public String getRevSisFisicoObservacion() {
        return this.revSisFisicoObservacion;
    }
    
    public void setRevSisFisicoObservacion(String revSisFisicoObservacion) {
        this.revSisFisicoObservacion = revSisFisicoObservacion;
    }
    public Date getRevSisFechaUlt() {
        return this.revSisFechaUlt;
    }
    
    public void setRevSisFechaUlt(Date revSisFechaUlt) {
        this.revSisFechaUlt = revSisFechaUlt;
    }
    public String getRevSisUsuario() {
        return this.revSisUsuario;
    }
    
    public void setRevSisUsuario(String revSisUsuario) {
        this.revSisUsuario = revSisUsuario;
    }
    public Set getHistoriases() {
        return this.historiases;
    }
    
    public void setHistoriases(Set historiases) {
        this.historiases = historiases;
    }




}


