package datos;
// Generated 22-may-2023 9:47:51 by Hibernate Tools 4.3.1



/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private int rolId;
     private String rolDescripcion;

    public Roles() {
    }

    public Roles(int rolId, String rolDescripcion) {
       this.rolId = rolId;
       this.rolDescripcion = rolDescripcion;
    }
   
    public int getRolId() {
        return this.rolId;
    }
    
    public void setRolId(int rolId) {
        this.rolId = rolId;
    }
    public String getRolDescripcion() {
        return this.rolDescripcion;
    }
    
    public void setRolDescripcion(String rolDescripcion) {
        this.rolDescripcion = rolDescripcion;
    }




}


