package datos;
// Generated 05-may-2023 11:01:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private int rolId;
     private String rolDescripcion;
     private Set usuarioses = new HashSet(0);

    public Roles() {
    }

	
    public Roles(int rolId, String rolDescripcion) {
        this.rolId = rolId;
        this.rolDescripcion = rolDescripcion;
    }
    public Roles(int rolId, String rolDescripcion, Set usuarioses) {
       this.rolId = rolId;
       this.rolDescripcion = rolDescripcion;
       this.usuarioses = usuarioses;
    }
   
    public int getRolId() {
        return this.rolId;
    }
    
    public void setRolId(int rolId) {
        this.rolId = rolId;
    }
    public String getRolDescripcion() {
        return this.rolDescripcion;
    }
    
    public void setRolDescripcion(String rolDescripcion) {
        this.rolDescripcion = rolDescripcion;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


