package datos;
// Generated 04-abr-2023 12:01:39 by Hibernate Tools 4.3.1



/**
 * Enfermedades generated by hbm2java
 */
public class Enfermedades  implements java.io.Serializable {


     private Integer enfId;
     private Historias historias;
     private String enfNombre;
     private String enfDescripcion;
     private String enfCodigoCie;

    public Enfermedades() {
    }

    public Enfermedades(Historias historias, String enfNombre, String enfDescripcion, String enfCodigoCie) {
       this.historias = historias;
       this.enfNombre = enfNombre;
       this.enfDescripcion = enfDescripcion;
       this.enfCodigoCie = enfCodigoCie;
    }
   
    public Integer getEnfId() {
        return this.enfId;
    }
    
    public void setEnfId(Integer enfId) {
        this.enfId = enfId;
    }
    public Historias getHistorias() {
        return this.historias;
    }
    
    public void setHistorias(Historias historias) {
        this.historias = historias;
    }
    public String getEnfNombre() {
        return this.enfNombre;
    }
    
    public void setEnfNombre(String enfNombre) {
        this.enfNombre = enfNombre;
    }
    public String getEnfDescripcion() {
        return this.enfDescripcion;
    }
    
    public void setEnfDescripcion(String enfDescripcion) {
        this.enfDescripcion = enfDescripcion;
    }
    public String getEnfCodigoCie() {
        return this.enfCodigoCie;
    }
    
    public void setEnfCodigoCie(String enfCodigoCie) {
        this.enfCodigoCie = enfCodigoCie;
    }




}


