package datos;
// Generated 06-abr-2023 11:50:51 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Historias generated by hbm2java
 */
public class Historias  implements java.io.Serializable {


     private Integer hisId;
     private Personas personas;
     private String hisMotivo;
     private String hisEnfermedadActual;
     private Date hisFechaUlt;
     private String hisUsuario;
     private int revisionSistemasRevSisId;
     private int signosSigId;
     private int resultadosResId;
     private int diagnosticosDiagnosticosId;
     private Set enfermedadeses = new HashSet(0);

    public Historias() {
    }

	
    public Historias(Personas personas, String hisMotivo, String hisEnfermedadActual, Date hisFechaUlt, String hisUsuario, int revisionSistemasRevSisId, int signosSigId, int resultadosResId, int diagnosticosDiagnosticosId) {
        this.personas = personas;
        this.hisMotivo = hisMotivo;
        this.hisEnfermedadActual = hisEnfermedadActual;
        this.hisFechaUlt = hisFechaUlt;
        this.hisUsuario = hisUsuario;
        this.revisionSistemasRevSisId = revisionSistemasRevSisId;
        this.signosSigId = signosSigId;
        this.resultadosResId = resultadosResId;
        this.diagnosticosDiagnosticosId = diagnosticosDiagnosticosId;
    }
    public Historias(Personas personas, String hisMotivo, String hisEnfermedadActual, Date hisFechaUlt, String hisUsuario, int revisionSistemasRevSisId, int signosSigId, int resultadosResId, int diagnosticosDiagnosticosId, Set enfermedadeses) {
       this.personas = personas;
       this.hisMotivo = hisMotivo;
       this.hisEnfermedadActual = hisEnfermedadActual;
       this.hisFechaUlt = hisFechaUlt;
       this.hisUsuario = hisUsuario;
       this.revisionSistemasRevSisId = revisionSistemasRevSisId;
       this.signosSigId = signosSigId;
       this.resultadosResId = resultadosResId;
       this.diagnosticosDiagnosticosId = diagnosticosDiagnosticosId;
       this.enfermedadeses = enfermedadeses;
    }
   
    public Integer getHisId() {
        return this.hisId;
    }
    
    public void setHisId(Integer hisId) {
        this.hisId = hisId;
    }
    public Personas getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Personas personas) {
        this.personas = personas;
    }
    public String getHisMotivo() {
        return this.hisMotivo;
    }
    
    public void setHisMotivo(String hisMotivo) {
        this.hisMotivo = hisMotivo;
    }
    public String getHisEnfermedadActual() {
        return this.hisEnfermedadActual;
    }
    
    public void setHisEnfermedadActual(String hisEnfermedadActual) {
        this.hisEnfermedadActual = hisEnfermedadActual;
    }
    public Date getHisFechaUlt() {
        return this.hisFechaUlt;
    }
    
    public void setHisFechaUlt(Date hisFechaUlt) {
        this.hisFechaUlt = hisFechaUlt;
    }
    public String getHisUsuario() {
        return this.hisUsuario;
    }
    
    public void setHisUsuario(String hisUsuario) {
        this.hisUsuario = hisUsuario;
    }
    public int getRevisionSistemasRevSisId() {
        return this.revisionSistemasRevSisId;
    }
    
    public void setRevisionSistemasRevSisId(int revisionSistemasRevSisId) {
        this.revisionSistemasRevSisId = revisionSistemasRevSisId;
    }
    public int getSignosSigId() {
        return this.signosSigId;
    }
    
    public void setSignosSigId(int signosSigId) {
        this.signosSigId = signosSigId;
    }
    public int getResultadosResId() {
        return this.resultadosResId;
    }
    
    public void setResultadosResId(int resultadosResId) {
        this.resultadosResId = resultadosResId;
    }
    public int getDiagnosticosDiagnosticosId() {
        return this.diagnosticosDiagnosticosId;
    }
    
    public void setDiagnosticosDiagnosticosId(int diagnosticosDiagnosticosId) {
        this.diagnosticosDiagnosticosId = diagnosticosDiagnosticosId;
    }
    public Set getEnfermedadeses() {
        return this.enfermedadeses;
    }
    
    public void setEnfermedadeses(Set enfermedadeses) {
        this.enfermedadeses = enfermedadeses;
    }




}


