package datos;
// Generated 28-mar-2023 16:08:58 by Hibernate Tools 4.3.1



/**
 * Historias generated by hbm2java
 */
public class Historias  implements java.io.Serializable {


     private Integer hisId;
     private Personas personas;
     private String hisMotivo;
     private String hisEnfermedadActual;
     private int revisionSistemasRevSisId;
     private int signosSigId;
     private int resultadosResId;
     private int diagnosticosDiagnosticosId;

    public Historias() {
    }

    public Historias(Personas personas, String hisMotivo, String hisEnfermedadActual, int revisionSistemasRevSisId, int signosSigId, int resultadosResId, int diagnosticosDiagnosticosId) {
       this.personas = personas;
       this.hisMotivo = hisMotivo;
       this.hisEnfermedadActual = hisEnfermedadActual;
       this.revisionSistemasRevSisId = revisionSistemasRevSisId;
       this.signosSigId = signosSigId;
       this.resultadosResId = resultadosResId;
       this.diagnosticosDiagnosticosId = diagnosticosDiagnosticosId;
    }
   
    public Integer getHisId() {
        return this.hisId;
    }
    
    public void setHisId(Integer hisId) {
        this.hisId = hisId;
    }
    public Personas getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Personas personas) {
        this.personas = personas;
    }
    public String getHisMotivo() {
        return this.hisMotivo;
    }
    
    public void setHisMotivo(String hisMotivo) {
        this.hisMotivo = hisMotivo;
    }
    public String getHisEnfermedadActual() {
        return this.hisEnfermedadActual;
    }
    
    public void setHisEnfermedadActual(String hisEnfermedadActual) {
        this.hisEnfermedadActual = hisEnfermedadActual;
    }
    public int getRevisionSistemasRevSisId() {
        return this.revisionSistemasRevSisId;
    }
    
    public void setRevisionSistemasRevSisId(int revisionSistemasRevSisId) {
        this.revisionSistemasRevSisId = revisionSistemasRevSisId;
    }
    public int getSignosSigId() {
        return this.signosSigId;
    }
    
    public void setSignosSigId(int signosSigId) {
        this.signosSigId = signosSigId;
    }
    public int getResultadosResId() {
        return this.resultadosResId;
    }
    
    public void setResultadosResId(int resultadosResId) {
        this.resultadosResId = resultadosResId;
    }
    public int getDiagnosticosDiagnosticosId() {
        return this.diagnosticosDiagnosticosId;
    }
    
    public void setDiagnosticosDiagnosticosId(int diagnosticosDiagnosticosId) {
        this.diagnosticosDiagnosticosId = diagnosticosDiagnosticosId;
    }




}


