package datos;
// Generated 28-mar-2023 16:08:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Medicamentos generated by hbm2java
 */
public class Medicamentos  implements java.io.Serializable {


     private Integer medId;
     private Tratamientos tratamientos;
     private String medNombre;
     private Set tratamientoses = new HashSet(0);

    public Medicamentos() {
    }

	
    public Medicamentos(Tratamientos tratamientos, String medNombre) {
        this.tratamientos = tratamientos;
        this.medNombre = medNombre;
    }
    public Medicamentos(Tratamientos tratamientos, String medNombre, Set tratamientoses) {
       this.tratamientos = tratamientos;
       this.medNombre = medNombre;
       this.tratamientoses = tratamientoses;
    }
   
    public Integer getMedId() {
        return this.medId;
    }
    
    public void setMedId(Integer medId) {
        this.medId = medId;
    }
    public Tratamientos getTratamientos() {
        return this.tratamientos;
    }
    
    public void setTratamientos(Tratamientos tratamientos) {
        this.tratamientos = tratamientos;
    }
    public String getMedNombre() {
        return this.medNombre;
    }
    
    public void setMedNombre(String medNombre) {
        this.medNombre = medNombre;
    }
    public Set getTratamientoses() {
        return this.tratamientoses;
    }
    
    public void setTratamientoses(Set tratamientoses) {
        this.tratamientoses = tratamientoses;
    }




}


