package datos;
// Generated 28-mar-2023 16:08:58 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personas generated by hbm2java
 */
public class Personas  implements java.io.Serializable {


     private Integer perId;
     private char perSexo;
     private Date perNac;
     private String perGrupoSanguineo;
     private Character perIdentidadGenero;
     private int antecedentesAntId;
     private String perProfesion;
     private Set historiases = new HashSet(0);
     private Set usuarioses = new HashSet(0);

    public Personas() {
    }

	
    public Personas(char perSexo, Date perNac, String perGrupoSanguineo, int antecedentesAntId, String perProfesion) {
        this.perSexo = perSexo;
        this.perNac = perNac;
        this.perGrupoSanguineo = perGrupoSanguineo;
        this.antecedentesAntId = antecedentesAntId;
        this.perProfesion = perProfesion;
    }
    public Personas(char perSexo, Date perNac, String perGrupoSanguineo, Character perIdentidadGenero, int antecedentesAntId, String perProfesion, Set historiases, Set usuarioses) {
       this.perSexo = perSexo;
       this.perNac = perNac;
       this.perGrupoSanguineo = perGrupoSanguineo;
       this.perIdentidadGenero = perIdentidadGenero;
       this.antecedentesAntId = antecedentesAntId;
       this.perProfesion = perProfesion;
       this.historiases = historiases;
       this.usuarioses = usuarioses;
    }
   
    public Integer getPerId() {
        return this.perId;
    }
    
    public void setPerId(Integer perId) {
        this.perId = perId;
    }
    public char getPerSexo() {
        return this.perSexo;
    }
    
    public void setPerSexo(char perSexo) {
        this.perSexo = perSexo;
    }
    public Date getPerNac() {
        return this.perNac;
    }
    
    public void setPerNac(Date perNac) {
        this.perNac = perNac;
    }
    public String getPerGrupoSanguineo() {
        return this.perGrupoSanguineo;
    }
    
    public void setPerGrupoSanguineo(String perGrupoSanguineo) {
        this.perGrupoSanguineo = perGrupoSanguineo;
    }
    public Character getPerIdentidadGenero() {
        return this.perIdentidadGenero;
    }
    
    public void setPerIdentidadGenero(Character perIdentidadGenero) {
        this.perIdentidadGenero = perIdentidadGenero;
    }
    public int getAntecedentesAntId() {
        return this.antecedentesAntId;
    }
    
    public void setAntecedentesAntId(int antecedentesAntId) {
        this.antecedentesAntId = antecedentesAntId;
    }
    public String getPerProfesion() {
        return this.perProfesion;
    }
    
    public void setPerProfesion(String perProfesion) {
        this.perProfesion = perProfesion;
    }
    public Set getHistoriases() {
        return this.historiases;
    }
    
    public void setHistoriases(Set historiases) {
        this.historiases = historiases;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


