package datos;
// Generated 28-mar-2023 16:08:58 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Resultados generated by hbm2java
 */
public class Resultados  implements java.io.Serializable {


     private Integer resId;
     private String resExamen;
     private Date resFecha;
     private String resResultado;
     private int historiasHisId;

    public Resultados() {
    }

	
    public Resultados(String resExamen, Date resFecha, int historiasHisId) {
        this.resExamen = resExamen;
        this.resFecha = resFecha;
        this.historiasHisId = historiasHisId;
    }
    public Resultados(String resExamen, Date resFecha, String resResultado, int historiasHisId) {
       this.resExamen = resExamen;
       this.resFecha = resFecha;
       this.resResultado = resResultado;
       this.historiasHisId = historiasHisId;
    }
   
    public Integer getResId() {
        return this.resId;
    }
    
    public void setResId(Integer resId) {
        this.resId = resId;
    }
    public String getResExamen() {
        return this.resExamen;
    }
    
    public void setResExamen(String resExamen) {
        this.resExamen = resExamen;
    }
    public Date getResFecha() {
        return this.resFecha;
    }
    
    public void setResFecha(Date resFecha) {
        this.resFecha = resFecha;
    }
    public String getResResultado() {
        return this.resResultado;
    }
    
    public void setResResultado(String resResultado) {
        this.resResultado = resResultado;
    }
    public int getHistoriasHisId() {
        return this.historiasHisId;
    }
    
    public void setHistoriasHisId(int historiasHisId) {
        this.historiasHisId = historiasHisId;
    }




}


