package datos;
// Generated 28-mar-2023 16:08:58 by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer usuId;
     private Personas personas;
     private String usuNombre;
     private String usuContra;

    public Usuarios() {
    }

    public Usuarios(Personas personas, String usuNombre, String usuContra) {
       this.personas = personas;
       this.usuNombre = usuNombre;
       this.usuContra = usuContra;
    }
   
    public Integer getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(Integer usuId) {
        this.usuId = usuId;
    }
    public Personas getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Personas personas) {
        this.personas = personas;
    }
    public String getUsuNombre() {
        return this.usuNombre;
    }
    
    public void setUsuNombre(String usuNombre) {
        this.usuNombre = usuNombre;
    }
    public String getUsuContra() {
        return this.usuContra;
    }
    
    public void setUsuContra(String usuContra) {
        this.usuContra = usuContra;
    }




}


